include: package:lint/analysis_options.yaml

linter:
  rules:
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Back to the 80s
    lines_longer_than_80_chars: true
