name: network_arch
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^2.1.0
  bloc: ^8.0.2
  carrier_info: ^2.0.4
  cupertino_icons: ^1.0.4
  device_preview: ^1.0.0
  elegant_notification: ^1.5.1
  enum_to_string: ^2.0.1
  dart_ping: ^6.1.2
  dart_ping_ios: ^1.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  hydrated_bloc: ^8.0.0
  introduction_screen: ^3.0.0
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  lan_scanner: ^3.2.0
  network_info_plus: ^2.1.2
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  permission_handler: ^9.1.0
  rxdart: ^0.27.3
  styled_widget: ^0.4.0+3
  wake_on_lan: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  dart_code_metrics: ^4.11.0
  import_sorter: ^4.6.0
  lint: ^1.8.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/dark_mode_map_style.txt
